name: Node.js CI

on:
  push:
    branches: [master, develop, develop/*]
  pull_request:
    branches: [master, develop, feature/*]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Angular dependencies
        run: npm ci
        working-directory: angular-frontend/

      - name: Build Angular app
        run: npm run build
        working-directory: angular-frontend/

      - name: Run Angular tests
        run: npm run test:prod
        working-directory: angular-frontend/
